print("\\ - Exibe uma barra")
print("\' - Exibe a aspa simples")
print('\" - Exibe a aspa dupla')
print('\a - Dá um bipe')
print('\b - Retrocesso')
print('\f - Avanço')
print('\n - Caractere de nova linha (enter)')
print('\r - Carriage return')
print('\t - Tab horizontal')
print('\v - Tab vertical')
